name: Auth API CD

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Dummy deploy step
              run: echo " Simulating deployment... (you can replace this with your actual deployment command)"
